variable "vpc_name" {}
variable "vpc_cidr" {}
variable "region" {}
variable "env" {}
variable "public_subnets_cidrs" {}
variable "private_subnets_cidrs" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "aws_eip" {}
variable "nat_gateway" {}
variable "route_table_private" {}
variable "internet_gateway" {}